version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      ignore:
          - dependency-name: "async-std"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "tokio"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
