[workspace]
resolver = "2"
members = [
    "packages/filerune",
    "packages/fusion",
    "tests",
    "bench",
]

[workspace.dependencies]
async-std = "^1.13.0"
tokio = "^1.40.0"

[workspace.dependencies.filerune_fusion]
path = "./packages/fusion"
features = ["all"]
