[package]
name = "bench"
edition = "2024"
publish = false

[[bench]]
name = "bench"
harness = false

[dependencies]
criterion = { workspace = true, features = ["async_std", "async_smol", "async_tokio"]}
filerune_fusion = { workspace = true }
tokio = { workspace = true }
